# Generated by Django 6.0.6 on 2026-06-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام خدمت")),
                (
                    "organization",
                    models.CharField(max_length=200, verbose_name="سازمان مسئول"),
                ),
                (
                    "organization_address",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="آدرس سازمان",
                    ),
                ),
                (
                    "documents",
                    models.TextField(verbose_name="مدارک مورد نیاز (با | جدا شود)"),
                ),
                ("steps", models.TextField(verbose_name="مراحل انجام (با | جدا شود)")),
                (
                    "cost",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="هزینه تقریبی"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="مدت زمان"
                    ),
                ),
                (
                    "more_info_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="لینک اطلاعات بیشتر"
                    ),
                ),
                ("keywords", models.TextField(blank=True, verbose_name="کلمات کلیدی")),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمات",
            },
        ),
    ]
