# Generated by Django 6.0.6 on 2026-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_faq_servicecenter_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="neighborhood",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="محله"
            ),
        ),
    ]
