# Generated by Django 6.0.6 on 2026-07-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecenter",
            name="coordinate",
            field=models.CharField(
                blank=True,
                help_text="مختصات جغرافیایی به فرمت 'lat,lng' مثلاً '35.6892,51.3890'",
                max_length=100,
                verbose_name="مختصات (عرض,طول)",
            ),
        ),
        migrations.AddField(
            model_name="servicecenter",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="کد پستی"),
        ),
        migrations.AddField(
            model_name="servicecenter",
            name="working_hours",
            field=models.TextField(blank=True, verbose_name="ساعت کاری"),
        ),
    ]
