# Generated by Django 6.0.6 on 2026-07-14 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0012_remove_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
            },
        ),
    ]
