# Generated by Django 6.0.6 on 2026-07-15 09:08

from django.db import migrations, models

import services.validators


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0013_reorder_comments_newest_first"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.IntegerField(
                db_index=True, default=0, verbose_name="ترتیب نمایش"
            ),
        ),
        migrations.AlterField(
            model_name="phoneverification",
            name="is_used",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="استفاده شده"
            ),
        ),
        migrations.AlterField(
            model_name="phoneverification",
            name="phone",
            field=models.CharField(
                db_index=True,
                max_length=11,
                validators=[services.validators.iranian_phone_number_validator],
                verbose_name="شماره تماس",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="نام خدمت"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="organization",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="سازمان مسئول"
            ),
        ),
        migrations.AlterField(
            model_name="servicecenter",
            name="city",
            field=models.CharField(db_index=True, max_length=100, verbose_name="شهر"),
        ),
    ]
