# Generated by Django 6.0.7 on 2026-07-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0015_comment_edit_delete_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCenterPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="شماره تماس")),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("main", "تلفن اصلی"),
                            ("fax", "فکس"),
                            ("mobile", "موبایل"),
                            ("other", "سایر"),
                        ],
                        default="main",
                        max_length=20,
                        verbose_name="برچسب",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="services.servicecenter",
                        verbose_name="مرکز",
                    ),
                ),
            ],
            options={
                "verbose_name": "شماره تماس مرکز",
                "verbose_name_plural": "شماره تماس\u200cهای مراکز",
                "ordering": ["order", "id"],
            },
        ),
    ]
