# Generated by Django 6.0.7 on 2026-07-18 12:47

from django.db import migrations, models

import services.validators


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0019_normalize_servicecenterphone_digits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecenterphone",
            name="phone",
            field=models.CharField(
                max_length=11,
                validators=[services.validators.center_phone_validator],
                verbose_name="شماره تماس",
            ),
        ),
    ]
