# Generated by Django 6.0.7 on 2026-07-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0020_alter_servicecenterphone_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecenter",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="توضیحات"),
        ),
    ]
