# Generated by Django 6.0.7 on 2026-07-19 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0021_servicecenter_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("service", "خدمت"), ("center", "مرکز")],
                        max_length=10,
                        verbose_name="نوع مورد",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("incorrect_info", "اطلاعات نادرست"),
                            ("outdated_info", "اطلاعات قدیمی"),
                            ("closed_center", "مرکز تعطیل شده"),
                            ("wrong_address", "آدرس اشتباه"),
                            ("wrong_phone", "شماره تلفن اشتباه"),
                            ("other", "سایر"),
                        ],
                        max_length=20,
                        verbose_name="دلیل گزارش",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="بررسی شده"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ بررسی"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت مدیر"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بررسی شده توسط",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="services.service",
                        verbose_name="خدمت",
                    ),
                ),
                (
                    "service_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="services.servicecenter",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش اطلاعات",
                "verbose_name_plural": "گزارش\u200cهای اطلاعات",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("service__isnull", False), ("target_type", "service")
                            ),
                            models.Q(
                                ("service_center__isnull", False),
                                ("target_type", "center"),
                            ),
                            _connector="OR",
                        ),
                        name="report_has_target",
                    )
                ],
            },
        ),
    ]
