# Generated by Django 6.0.7 on 2026-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0022_add_inforeport"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecenter",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="service_centers",
                to="services.service",
                verbose_name="خدمات",
            ),
        ),
    ]
