# Generated by Django 6.0.7 on 2026-07-19 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0024_copy_service_fk_to_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicecenter",
            name="service",
        ),
    ]
