# Generated by Django 6.0.7 on 2026-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0025_remove_service_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneverification",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="تعداد تلاش\u200cهای ناموفق"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="documents",
            field=models.TextField(verbose_name="مدارک مورد نیاز"),
        ),
        migrations.AlterField(
            model_name="service",
            name="steps",
            field=models.TextField(verbose_name="مراحل انجام"),
        ),
    ]
