# Generated by Django 6.0.7 on 2026-07-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0027_add_commentreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
    ]
